services:
  - type: web
    name: resilient-email-service
    env: docker
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/ResilientEmailService-1.0.0.jar
    repo: https://github.com/dilipdeadpool/ResilientEmailServiceSpringBoot
    branch: main
    plan: free
